### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by bast** [bast/reproducible-rse#1]
- [x] notebooks
- [x] nbdime and github
- [x] how to track data and models
- [x] licenses for models
- [x] example data
- [x] google collab and dependencies
- [x] GPU/AI on a cluster
- [x] sharing sensitive stuff
- [x] binder
